apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httppod
  name: httppod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httppod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httppod
    spec:
      containers:
      - image: registry.ocp4.example.com:8443/ubi8/httpd-24
        name: httpd-24
        ports:
        - containerPort: 8080
        resources: {}
status: {}
