apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod
  name: pod
spec:
  containers:
  - image: registry.ocp4.example.com:8443/ubi8/httpd-24
    name: jack
    ports:
    - containerPort: 8080

  - image: docker.io/library/httpd
    name: jacker
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
